### ISSUE TITLE
Any versions compatible with Gradle 6.9.2?

### ISSUE THREAD

**Issue by EM-Creations** [jjohannes/java-module-dependencies#16]
Hi,

Are any versions of this plugin compatible with Gradle 6.9.2?

Thanks!

**Comment by jjohannes** [comment]
No. The plugin uses the following features that require Gradle 7+

- Version Catalog
- _DependencyHandler.addProvider(...)_ API
- `providers.fileContents(...).asText` during configuration time in a way that is compatible with the _configuration cache_ (requires 7.4+ to be used like it is used now)

However, none of these are necessary for the **core functionality** of this plugin. I think it should be possible to get the plugin's core functionality working with 6.9+ (probably 6.4+) but it will make the code more complicated.

What's blocking you from upgrading to Gradle 7?

**Comment by EM-Creations** [comment]
> No. The plugin uses the following features that require Gradle 7+
> 
> * Version Catalog
> * _DependencyHandler.addProvider(...)_ API
> * `providers.fileContents(...).asText` during configuration time in a way that is compatible with the _configuration cache_ (requires 7.4+ to be used like it is used now)
> 
> However, none of these are necessary for the **core functionality** of this plugin. I think it should be possible to get the plugin's core functionality working with 6.9+ (probably 6.4+) but it will make the code more complicated.
> 
> What's blocking you from upgrading to Gradle 7?

Hi,

It's not a problem now, we were able to upgrade our project thank you.
